CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER CONSTRAINT PK_CUTO PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    LOCATION VARCHAR2(100) NOT NULL ,
    PHONE VARCHAR2(100) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL
);


CREATE TABLE TECHNICIANS (
    TECH_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    ZONE VARCHAR2(50)NOT NULL,
    IS_AVAILABLE CHAR(1) CHECK (is_available IN ('Y','N')) NOT NULL,
    PHONE VARCHAR2(100) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE COMPLAINTS (
    COMPLAINT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER REFERENCES customers(customer_id),
    COMPLAINT_TYPE VARCHAR2(100),
    STATUS VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    RESOLVED_AT DATE,
    ASSIGNED_TECHNICIAN NUMBER REFERENCES technicians(tech_id)
);


CREATE TABLE STATUS_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    COMPLAINT_ID NUMBER REFERENCES complaints(complaint_id),
    STATUS VARCHAR2(20),
    CHANGED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE ESCALATIONS (
    ESCALATION_ID NUMBER PRIMARY KEY,
    COMPLAINT_ID NUMBER REFERENCES complaints(complaint_id),
    LEVELS NUMBER,
    TRIGGERED_AT DATE DEFAULT SYSDATE
);